feat!: added file download tracking (#260)
DataBiosphere/findable-ui pull request #263
Opened 2024-11-12 07:55 UTC by jpaten

### Changes
- Added `file_downloaded` event and relevant models as specified in #260
- Added call to this event in `AzulFileDownload`, adding new optional props as needed

2024-11-12 23:01 UTC, MillenniumFalconMechanic requested changes
Looks good, thanks Jonah! I've added a couple of comments. Can you also double-check the GTM parameter value limit? I was under the impression that parameter names are limited to 40 but parameter values can be 100.

2024-11-13 08:02 UTC, jpaten commented
@MillenniumFalconMechanic my bad, I read the wrong limit, it is 100 characters. Some file names come very close to that, but I couldn't find any that have more than 100 characters, so this approach is probably fine

2024-11-13 08:05 UTC, jpaten commented on src/components/Index/components/AzulFileDownload/azulFileDownload.tsx
> +  relatedEntityName?: string[]; // An array of names of the file's datasets / projects
Sounds good, I'll make that change

2024-11-13 18:07 UTC, jpaten commented
TODO: writeup breaking change and tag Fran

2024-11-13 20:06 UTC, jpaten commented
#### Breaking Changes @frano-m 
- AzulFileDownloaded has the following new required props
  - `entityName`
    - string
    - The filename for the file being downloaded
  - `relatedEntityId`
    - string
    - The ID(s) of the dataset(s) or project(s) associated with the file
    - If there are multiple different associated datasets or projects, they should be stringified in the `viewModelBuilder` before being passed here
  - `relatedEntityName`
    - string
    - The name(s) of the dataset(s) or project(s) associated with the file
    - If there are multiple different associated datasets or projects, they should be stringified in the `viewModelBuilder` before being passed here

2024-11-14 00:16 UTC, frano-m commented on tests/azulFileDownload.test.tsx
> +  const TRACKING_PARAMETERS = {
@jpaten nice!

2024-11-14 00:16 UTC, frano-m approved these changes
LGTM! Thank you @jpaten 🚀

2024-11-14 18:14 UTC, MillenniumFalconMechanic approved these changes
LGTM, thanks Jonah!

2024-11-14 18:14 UTC, MillenniumFalconMechanic commented on tests/azulFileDownload.test.tsx
> +  const TRACKING_PARAMETERS = {
Agreed!

2024-11-14 18:39 UTC, merged